### PR TITLE
fix: keep text search for non-speech-support browsers

### PR DESCRIPTION
**Pull request by vietthedev**
Keep the search bar for text search for non-speech support browsers like Firefox

### CODE REVIEW

**Comment by vietthedev** [comment]
Hhi @AyushVerma2772, can you take a look?

**Comment by AyushVerma2772** [comment]
search bar for text search for non-speech support browsers like Firefox

**Review by AyushVerma2772 — COMMENTED** [review]
search bar for text search for non-speech support browsers like Firefox

**Comment by vietthedev** [comment]
@AyushVerma2772 I made the search bar visible for Firefox for users to search by text. Previous code made the whole search bar hidden for browsers not supporting speech.

**Pull request closed without merging**
